setwd("E:/Bed/R/Coursera/")
X_train<-read.table("./data/train/X_train.txt",sep="",header=FALSE,as.is=TRUE)
X_test<-read.table("./data/test/X_test.txt",sep="",header=FALSE,as.is=TRUE)
Y_train<-read.table("./data/train/y_train.txt",sep="",header=FALSE,as.is=TRUE)
Y_test<-read.table("./data/test/y_test.txt",sep="",header=FALSE,as.is=TRUE)
activity_labels<-read.table("./data/activity_labels.txt",sep="",header=FALSE,as.is=TRUE)
Subject_train<-read.table("./data/train/subject_train.txt",sep="",header=FALSE,as.is=TRUE)
Subject_test<-read.table("./data/test/subject_test.txt",sep="",header=FALSE,as.is=TRUE)
Data_all<-rbind(cbind(Subject_train,Y_train,X_train),cbind(Subject_test,Y_test,X_test))
X_features<-read.table("./data/features.txt",sep="",header=FALSE,as.is=TRUE)
mean.vect<-grep("mean()",X_features$V2,fixed=TRUE)
std.vect<-grep("std()",X_features$V2,fixed=TRUE)
data<-Data_all[,c(2,1,mean.vect+3,std.vect+3)]
colnames(data)<-c("activitynumber","subject",X_features[c(mean.vect,std.vect),"V2"])
data<-merge(data,activity_labels,by.x="activitynumber",by.y="V1",all.x=TRUE,sort=FALSE)
colnames(data)<-c("activitynumber","subject",X_features[c(mean.vect,std.vect),"V2"],"activity")
data$subject<-as.factor(data$subject)
data$activity<-as.factor(data$activity)
split.data<-split(data,list(data$subject,data$activity))
mean.df<-sapply(split.data,function(x) colMeans(x[,-c(1,2,dim(data)[2])],na.rm=TRUE))
library(reshape);df<-melt(mean.df);colnames(df)<-c("measure","factor","mean")
df$measure=as.character(df$measure);df$factor=as.character(df$factor)
splitnames=strsplit(df[,"factor"],"\\.")
fullname=t(sapply(splitnames,function(.xyz) c(subject=.xyz[1],activity=.xyz[2])))
df$subject=as.numeric(fullname[,1]);df$activity=as.character(fullname[,2])
tidy<-df[,c("activity","subject","measure","mean")]
write.table(tidy,file="tidy.txt",sep="\t",quote=FALSE)
